<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel' => 'Prekliči',
    'Confirmation' => 'Obvestilo',
    'Information' => 'Obvestilo',
    'Ok' => 'Ok',
    'Update profile?' =>'Posodobi profil',
    'Warning!'=>'Opozorilo!',
    'Error'=>'Napaka!',

    // Popup warnings
    'You have successfully updated advertisement!'=>'Uspešno ste posodobili oglas!',
    'Operation successful!' =>'Zahteva uspešno opravljena',
    'You are not the owner!'=>'Vi niste lastnik!',
    'Request denied'=>'Zahteva zavrnjena',
    'You have successfully deleted advertisement!' =>'Uspešno ste izbrisali oglas!',


    //Growl messages
    'You have already posted advert with this specifics'=>'Oglas ste že objavili s temi specifikacijami',
    'Advert not created'=>'Oglas ni bil objavnjen!',
    'You have succesfuly posted advertisment!'=>'Uspešno ste objavili oglas.',
    'Add created'=>'Oglas je objavnjen!',
    'Review declined!'=>'Ocena zavrnjena!',
    'You have declined review for your profile.'=>'Zavrnili ste oceno uporabnika.',
    'Review accepted!'=>'Ocena je sprejeta!',
    'Review will be shown on your profile.'=>'Ocena bo prikazana na vašem profilu.',
    'Are you sure you want to publish this review?'=>'Ali ste prepričani da želite objaviti to vsebino?',
    'You have {n,plural,=1{# advert} other{# adverts}} about to expire in less than 4 days!'=>'Pozor! Imate {n,plural,=1{# oglas} =2{# oglasa} other{# oglasev}},  {n,plural,=1{kateremu} =2{katerima} other{katerim}} veljavnost bo potekla v manj kot štirih dneh!',
    'An email has been sent with instructions for resetting your password!'=>'E-mail sporočilo je bilo poslano z navodili za ponastavitev gesla!',
    'Something went wrong your account has not been confirmed!'=>'Nekaj je šlo narobe, vaš račun ni bil potrjen!',
];
