<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel' => 'Annuler',
    'Confirmation' => 'Avis',
    'Information' => 'Information',
    'Ok' => 'Ok',
    'Update profile?' =>'Mettre à jour le profil?',
    'Warning!'=>'Attention!',
    'Error'=>'Erreur!',




    // Popup warnings
    'You have successfully updated advertisement!'=>'Vous avez mis à jour avec succès l\'annonce!',
    'Operation successful!' =>'Opération réussie!',
    'You are not the owner!'=>'Vous n\'êtes pas le propriétaire!',
    'You have successfully deleted advertisement!' =>'\'Vous avez supprimé la publicité!\'',
    'Request denied'=>'Demande refusée',

    //Growl messages
    'You have already posted advert with this specifics'=>'',
    'Advert not created'=>'',
    'You have succesfuly posted advertisment!'=>'',
    'Add created'=>'',
    'Review declined!'=>'',
    'You have declined review for your profile.'=>'',
    'Review accepted!'=>'',
    'Review will be shown on your profile.'=>'',
    'Are you sure you want to publish this review?'=>'',
    'You have {n,plural,=1{# advert} other{# adverts}} about to expire in less than 4 days!'=>'',
    'An email has been sent with instructions for resetting your password!'=>'Un email a été envoyé avec des instructions pour réinitialiser votre mot de passe!',
    'Something went wrong your account has not been confirmed!'=>'Quelque chose s\'est mal passé, votre compte n\'a pas été confirmé!',

];
