<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel' => 'Annuler',
    'Confirmation' => 'Confirmer',
    'Information' => 'Information',
    'Ok' => 'Ok',
    'Update profile?' =>'Mettre à jour le profil?',
    'Warning!'=>'Attention!',
    'Error'=>'Erreur!',




    // Popup warnings
    'You have successfully updated advertisement!'=>'Vous avez mis à jour l\'annonce avec succès!',
    'Operation successful!' =>'Opération réussie!',
    'You are not the owner!'=>'Vous n\'êtes pas le propriétaire!',
    'You have successfully deleted advertisement!' =>'\'Vous avez supprimé la publicité avec succès!\'',
    'Request denied'=>'Demande refusée',

    //Growl messages
    'You have already posted advert with this specifics'=>'Vous avez déjà posté une annonce identique',
    'Advert not created'=>'L\'annonce n\'a pas été crée',
    'You have succesfuly posted advertisment!'=>'Vous avez posté votre annonce avec succès',
    'Add created'=>'Annonce crée',
    'Review declined!'=>'Commentaire refusé',
    'You have declined review for your profile.'=>'Vous avez refusé le commentaire pour votre profil',
    'Review accepted!'=>'Commentaire accepté!',
    'Review will be shown on your profile.'=>'Le commentaire sera publié sur votre profil',
    'Are you sure you want to publish this review?'=>'Êtes-vous sûr se bien vouloir publié ce commentaire?',
    'You have {n,plural,=1{# advert} other{# adverts}} about to expire in less than 4 days!'=>'Vous avez {n,plural,=1{# annonce} other{# annonces}} expirant dans moins de 4 jours!',
    'An email has been sent with instructions for resetting your password!'=>'Un email vous a été envoyé avec les instructions pour réinitialiser votre mot de passe!',
    'Something went wrong your account has not been confirmed!'=>'Une erreur s\'est produite, votre compte n\'a pas été confirmé!',

];

